# Generated by Django 4.0.6 on 2022-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('panNumber', models.CharField(max_length=30)),
                ('panPhoto', models.ImageField(upload_to='')),
                ('influencerName', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('referrelCode', models.CharField(max_length=40, unique=True)),
                ('addCustomer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcustomer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
