# Generated by Django 4.0.6 on 2022-07-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('panNumber', models.CharField(max_length=30, verbose_name='Pan Number')),
                ('panPhoto', models.ImageField(upload_to='PanCard/Influencer/', verbose_name='Pan Photo')),
                ('totalPoint', models.IntegerField(default=0, verbose_name='Total Point')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('influencerName', models.CharField(max_length=30, verbose_name='Influencer Name')),
                ('referrelCode', models.CharField(max_length=40, unique=True, verbose_name='Referrel Code')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
