# Generated by Django 4.0.6 on 2022-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0002_remove_addinfluencer_addcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfluencer',
            name='panPhoto',
            field=models.ImageField(upload_to='PanCard/Influencer/'),
        ),
    ]
