# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0003_alter_addinfluencer_panphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addinfluencer',
            name='panPhoto',
            field=models.ImageField(upload_to='PanCard/Influencer/<django.db.models.fields.CharField>'),
        ),
    ]
