# Generated by Django 4.1 on 2022-09-06 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0007_alter_companyinventory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festial', models.IntegerField(blank=True, default=0, null=True)),
                ('occasion', models.IntegerField(blank=True, default=0, null=True)),
                ('misc', models.IntegerField(blank=True, default=0, null=True)),
                ('geography', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.companyinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
