# Generated by Django 4.1 on 2022-09-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Influencer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinfluencer',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='addinfluencer',
            name='totalPoint',
        ),
        migrations.RemoveField(
            model_name='addinfluencer',
            name='updatedOn',
        ),
    ]
