# Generated by Django 4.0.6 on 2022-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('panNumber', models.CharField(max_length=30)),
                ('panPhoto', models.ImageField(upload_to='')),
                ('dealerName', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('referrelCode', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DealerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productCategory', models.CharField(max_length=255)),
                ('productQuantity', models.CharField(max_length=255)),
                ('dealer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.adddealer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
