# Generated by Django 4.0.6 on 2022-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddealer',
            name='panPhoto',
            field=models.ImageField(upload_to='PanCard/Dealer/'),
        ),
    ]
