# Generated by Django 4.0.6 on 2022-07-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_alter_adddealer_panphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddealer',
            name='panPhoto',
            field=models.ImageField(upload_to='PanCard/Dealer/<django.db.models.fields.CharField>'),
        ),
    ]
