# Generated by Django 4.0.6 on 2022-07-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dealer', '0001_initial'),
        ('Influencer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30, verbose_name='Company Name')),
                ('dealerList', models.ManyToManyField(blank=True, to='Dealer.adddealer', verbose_name='Dealer List')),
                ('influencerList', models.ManyToManyField(blank=True, to='Influencer.addinfluencer', verbose_name='Influencer List')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255, verbose_name='Product Name')),
                ('productCategory', models.CharField(max_length=255, verbose_name='Product Category')),
                ('productQuantity', models.CharField(max_length=255, verbose_name='Product Quantity')),
                ('companyName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placedOn', models.DateTimeField(blank=True, null=True)),
                ('expectedDelievery', models.DateTimeField(blank=True, null=True)),
                ('orderFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.adddealer', verbose_name='Dealer Who Ordered')),
                ('orderTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany', verbose_name='Company Whom Ordered')),
                ('orders', models.ManyToManyField(blank=True, to='Company.companyinventory', verbose_name='Order Placed')),
            ],
        ),
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30, verbose_name='Customer Name')),
                ('customerPhoneNumber', models.BigIntegerField(verbose_name='Phone Number')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('companyInterested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany', verbose_name='Interested Company')),
                ('dealerName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.adddealer', verbose_name='Dealer Name')),
                ('influencedThrough', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Influencer.addinfluencer', verbose_name='Influencer (if any)')),
                ('interestedProduct', models.ManyToManyField(blank=True, to='Company.companyinventory', verbose_name='Interested Product')),
            ],
        ),
    ]
