# Generated by Django 4.0.6 on 2022-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productCategory', models.CharField(max_length=255)),
                ('productQuantity', models.CharField(max_length=255)),
                ('companyName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30)),
                ('customerPhoneNumber', models.BigIntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('companyInterested', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany')),
                ('dealerName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.adddealer')),
            ],
        ),
    ]
