# Generated by Django 4.0.6 on 2022-07-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dealer', '0001_initial'),
        ('Influencer', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcustomer',
            name='influencedThrough',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Influencer.addinfluencer'),
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='interestedProduct',
            field=models.ManyToManyField(blank=True, to='Company.companyinventory'),
        ),
        migrations.AddField(
            model_name='addcompany',
            name='dealerList',
            field=models.ManyToManyField(blank=True, to='Dealer.adddealer'),
        ),
        migrations.AddField(
            model_name='addcompany',
            name='influencerList',
            field=models.ManyToManyField(blank=True, to='Influencer.addinfluencer'),
        ),
    ]
