# Generated by Django 4.0.6 on 2022-07-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
        ('Influencer', '0002_remove_addinfluencer_addcustomer'),
        ('Company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='companyInterested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.addcompany'),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='dealerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.adddealer'),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='influencedThrough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Influencer.addinfluencer'),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='interestedProduct',
            field=models.ManyToManyField(blank=True, null=True, to='Company.companyinventory'),
        ),
    ]
