# Generated by Django 4.0.6 on 2022-07-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_addcustomer_companyinterested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='interestedProduct',
            field=models.ManyToManyField(blank=True, to='Company.companyinventory'),
        ),
    ]
