# Generated by Django 4.0.6 on 2022-09-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companyinventory_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqueue',
            name='orderFrom',
        ),
        migrations.RemoveField(
            model_name='orderqueue',
            name='orderTo',
        ),
    ]
