# Generated by Django 4.0.6 on 2022-09-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_remove_orderqueue_orderfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustomer',
            name='companyInterested',
        ),
    ]
