# Generated by Django 4.0.6 on 2022-09-02 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0004_remove_addcustomer_companyinterested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcustomer',
            name='dealerName',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DealerName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='influencedThrough',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Influencer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='InfluencerName', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addcustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
