# Generated by Django 4.1 on 2022-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_alter_addcustomer_dealername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinventory',
            name='price',
            field=models.IntegerField(default=5000, max_length=255, verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='orderValue',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
