# Generated by Django 4.1 on 2022-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_companyinventory_price_orderqueue_ordervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinventory',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='Product Price'),
        ),
    ]
