# Generated by Django 4.1 on 2022-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_alter_companyinventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinventory',
            name='point',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Product Ponits'),
        ),
    ]
