# Generated by Django 4.0.6 on 2022-09-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_companyinventory_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderqueue',
            name='orderedProducts',
        ),
        migrations.AddField(
            model_name='orderqueue',
            name='orderedProducts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyinventory', verbose_name='Order Placed'),
        ),
    ]
