# Generated by Django 4.0.6 on 2022-09-09 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0009_remove_orderqueue_orderedproducts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcustomer',
            name='interestedProduct',
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='interestedProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.companyinventory', verbose_name='Interested Product'),
        ),
    ]
