# Generated by Django 4.1 on 2022-09-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_alter_dealerinventory_dealer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddealer',
            name='createdOn',
        ),
        migrations.RemoveField(
            model_name='adddealer',
            name='totalPoint',
        ),
        migrations.RemoveField(
            model_name='adddealer',
            name='updatedOn',
        ),
        migrations.AddField(
            model_name='dealerinventory',
            name='price',
            field=models.IntegerField(default=5000, max_length=255, verbose_name='Product Price'),
        ),
    ]
