# Generated by Django 4.1 on 2022-09-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0003_remove_adddealer_createdon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerinventory',
            name='price',
            field=models.IntegerField(default=5000, verbose_name='Product Price'),
        ),
    ]
