# Generated by Django 4.1 on 2022-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0004_alter_dealerinventory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerinventory',
            name='point',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Product Ponits'),
        ),
    ]
