# Generated by Django 4.1 on 2022-08-06 07:05

import Users.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Users.manager.UserManager()),
            ],
        ),
    ]
